### PR TITLE
Bump Fedora version to 26

### PR DESCRIPTION
**Pull request by r7vme**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
CI is still failing.

**Comment by calvix** [comment]
I saw same issue with `iputils` + fedora on CircleCI too, I have no idea why this happening and this error is only native to CircleCI I could not reproduce  on my local machine :(

**Comment by r7vme** [comment]
Okay, so the problem with fails were related to underlay docker environment in CIrcleCI. Old docker in Ubuntu 14.04 uses aufs, which did [not support extended file attributes](https://github.com/moby/moby/issues/1070) in old version. Which required by iputils package, as it sets capability to `ping`.

After searching internet and CircleCI forums i've found that potentially [newer Ubuntu image](https://discuss.circleci.com/t/error-with-yum-update-in-docker-centos-7/8671) is used in 2.0.

@JosephSalisbury please take look on circle 2.0 configuration.

**Comment by JosephSalisbury** [comment]
Oh, awesome on sorting out the config.

**Pull request merged**
