### PR TITLE
Expose qemu monitor and add shutdown script

### PR DESCRIPTION
**Pull request by r7vme**
Allow shutdown VM gracefully.

Related: https://github.com/giantswarm/kvm-operator/pull/334
Fixes: https://github.com/giantswarm/kvm-operator/issues/333

### CODE REVIEW

**Comment by r7vme** [comment]
Good point.

`terminationGracePeriodSeconds` is 30 sec by default, so after this timeout k8s will send regular SIGTERM.

> If the hook hangs during execution, the Pod phase stays in a Terminating state and is killed after terminationGracePeriodSeconds of pod ends

https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

**Comment by xh3b4sd** [comment]
> `terminationGracePeriodSeconds` is 30 sec by default, so after this timeout k8s will send regular SIGTERM.

You mean `SIGKILL` right? `SIGTERM` is being send in the first place and after the containers couldn't be shut down gracefully in time Kubernetes sends a `SIGKILL`. See https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.

**Comment by xh3b4sd** [comment]
Do we know how long the qemu termination takes round about?

**Comment by r7vme** [comment]
You're right, `terminationGracePeriodSeconds` is time to wait for preStop hook + regular SIGTERM. After `terminationGracePeriodSeconds` always will be sent `SIGKILL`.

Yes, for me for masters/worker vms (w/o lots of pods) it was about 1-3 seconds.

**Pull request merged**
